[package]
name = "web-server"
edition = "2024"

[dependencies]
full = "0.3.0"
futures = "0.3.31"
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full"] }
tokio-tungstenite = "0.26.2"
warp = "0.3.7"
